on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Run your project's build step
      - name: Build 
        run: wget https://github.com/barnumbirr/zola-debian/releases/download/v0.15.3-1/zola_0.15.3-1_amd64_bullseye.deb && sudo dpkg -i zola_0.15.3-1_amd64_bullseye.deb && zola check && zola build
      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: zola-test # e.g. 'my-project'
          directory: public # e.g. 'dist'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
