name: Deploy to Cloudflare Pages

on: [push]

env: 
  ZOLA_VERSION: v0.15.3
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      # Run your project's build step
      - name: Build 
        run: |
          wget https://github.com/getzola/zola/releases/download/$ZOLA_VERSION/zola-$ZOLA_VERSION-x86_64-unknown-linux-gnu.tar.gz 
          tar -C /usr/local/bin -xzvf zola-$ZOLA_VERSION-x86_64-unknown-linux-gnu.tar.gz
          zola check
          zola build
          ls -la ./public/
      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: zola-test # e.g. 'my-project'
          directory: public # e.g. 'dist'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
